backend:
  name: github
  repo: lukestorry/season-of-the-vegan
  branch: main
media_folder: public/img
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Recipes'
    name: 'recipes'
    folder: 'content/recipes'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', allow_multiple: false, required: false }
      - { label: 'Prep Time (mins)', name: 'prep_time', widget: 'number', value_type: 'int', min: 0, max: 420 }
      - { label: 'Cook Time (mins)', name: 'cook_time', widget: 'number', value_type: 'int', min: 0, max: 420 }
      - {
          label: 'Ingredients',
          name: 'ingredients',
          widget: 'markdown',
          buttons: ['bulleted-list', 'heading-five', 'bold', 'italic', 'link'],
          editor_components: [],
        }
      - {
          label: 'Method',
          name: 'body',
          widget: 'markdown',
          buttons: ['bulleted-list', 'heading-five', 'bold', 'italic', 'link'],
          editor_components: ['image'],
        }
